//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wsdemo8Entities1 : DbContext
    {
        public wsdemo8Entities1()
            : base("name=wsdemo8Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent_oborudovan> Abonent_oborudovan { get; set; }
        public virtual DbSet<Magistral> Magistral { get; set; }
        public virtual DbSet<Seti_dostupa> Seti_dostupa { get; set; }
    }
}
