//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNSDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCRM
    {
        public int Id { get; set; }
        public string NumberOrder { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string LS { get; set; }
        public string Services { get; set; }
        public string VidServices { get; set; }
        public string TypeServices { get; set; }
        public string State { get; set; }
        public string Problem { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public string TypeProblem { get; set; }
        public string Device { get; set; }
    }
}
