//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNSDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class StreetSPB
    {
        public int Id { get; set; }
        public string NameStreet { get; set; }
        public string Ploshad { get; set; }
        public int CountPeople { get; set; }
        public int CountMetro { get; set; }
        public string TypeBuild { get; set; }
    }
}
