//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNSDesktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tnsEntities : DbContext
    {
        public tnsEntities()
            : base("name=tnsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbonentDevices> AbonentDevices { get; set; }
        public virtual DbSet<Abonents> Abonents { get; set; }
        public virtual DbSet<ComboTarifs> ComboTarifs { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<LineDevices> LineDevices { get; set; }
        public virtual DbSet<Magistrals> Magistrals { get; set; }
        public virtual DbSet<MF> MF { get; set; }
        public virtual DbSet<OrderCRM> OrderCRM { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Staffs> Staffs { get; set; }
        public virtual DbSet<StreetSPB> StreetSPB { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarifs> Tarifs { get; set; }
        public virtual DbSet<TypesDoc> TypesDoc { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
