//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigruzkaPDFDoc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ws05Entities : DbContext
    {
        public static ws05Entities _context;
        public ws05Entities()
            : base("name=ws05Entities")
        {
        }
        public static ws05Entities GetContext()
        {
            if (_context == null)
                _context = new ws05Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllAbonts> AllAbonts { get; set; }
    }
}
